### ISSUE TITLE
URL isn't copied to clipboard on Linux

### ISSUE THREAD

**Issue by twentytwoo** [psicotropicos/hyper-fileio#1]
Using `Linux amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64 GNU/Linux` on `Hyper version 1.3.1`

**Comment by psicotropicos** [comment]
Hi, thanks for to report, I will try to reproduce the error and fix it as soon possible.

**Comment by psicotropicos** [comment]
@twentytwoo I released a new version, can you test?

**Comment by twentytwoo** [comment]
Sorry, I'm not using hyperterm anymore :/
